# -*- coding: utf-8 -*-
"""Image_to_Pencil_Sketch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15M81PYkY5gFAYwA8wRfo4N5KRxhIErZw

# Converting image to pencil sketch
"""

# importing the libraries
import cv2
from google.colab.patches import cv2_imshow

def display(img):
  cv2_imshow(img)

#displaying the image
img=cv2.imread("/content/image.jpg")
display(img)

#Changing the scale of image to gray
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
display(gray)

#Inverting the new gray scale
inverted = 255 - gray
display(inverted)

#Processing to blur the image using Gaussian Function
blurred = cv2.GaussianBlur(inverted, (21, 21), 0)
display(blurred)

inverted_blurred = 255 - blurred
pencil_sketch = cv2.divide(gray, inverted_blurred, scale=256)
display(pencil_sketch)

"""Thank You!!"""