# Generated by Django 3.2.7 on 2021-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnum', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('blg', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
    ]
